# Generated by Django 3.2.5 on 2021-09-13 14:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('can_expire_links', models.BooleanField(default=False)),
                ('original_link_access', models.BooleanField(default=False)),
                ('thumbnail_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('height', models.PositiveIntegerField()),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseimage')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.accountplan'),
        ),
    ]
