# Generated by Django 3.2.5 on 2021-09-13 17:06

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210913_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='base_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseimage', validators=[core.validators.validate_file_extension]),
        ),
    ]
