# Generated by Django 3.2.5 on 2021-09-13 21:14

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_thumbnail_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='base_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseimage'),
        ),
    ]
