# Generated by Django 3.2.5 on 2021-09-13 21:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210913_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to='images/', validators=[core.validators.validate_file_extension]),
        ),
    ]
