# Generated by Django 3.2.5 on 2021-09-14 16:02

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_baseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=core.models.base_image_file_path, validators=[core.validators.validate_file_extension]),
        ),
    ]
