# Generated by Django 3.2.5 on 2021-09-15 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='available_until',
        ),
        migrations.AddField(
            model_name='link',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='link',
            name='duration',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
