# Generated by Django 3.2.5 on 2021-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210915_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='name',
            field=models.CharField(default='Thumbnailname', max_length=150),
        ),
    ]
