# Generated by Django 3.2.5 on 2021-09-15 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_thumbnail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='duration',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
