# Generated by Django 3.2.5 on 2021-09-16 12:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_link_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(upload_to=core.models.thumbnail_file_path),
        ),
    ]
